name: Move assigned issues to Todo

on:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: DynamoWishlist
          column: Todo
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
