name: Move new issues to Triage

on:
  issues:
    types: [opened]

jobs:
  add-issue-to-project:
    name: Add issue to triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/avidit/projects/1
          github-token: ${{ secrets.ISSUES_TOKEN }}
