name: Project automation

on:
  issues:
    types:
      - opened
      - reopened
      - assigned
      - closed

jobs:
  issue_opened_or_reopened:
    name: issue opened or reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to triage
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.ISSUES_TOKEN }}
          user: avidit
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Triage

  issue_labeled:
    name: issue labeled
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled'
    steps:
      - name: Move issue to triage
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.ISSUES_TOKEN }}
          user: avidit
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Backlog

  issue_assigned:
    name: issue assigned
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'assigned'
    steps:
      - name: Move issue to triage
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.ISSUES_TOKEN }}
          user: avidit
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Todo

  issue_closed:
    name: issue closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to done
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.ISSUES_TOKEN }}
          user: avidit
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Done
